version: '3.7'

services: 
  web:
    build: .
    command: bundle exec middleman server
    volumes:
      - '.:/myapp'
    image: crowdmarkos/middleman-demo:firsttry
    ports:
      - '4567:4567'
      - '1234:1234'
